jwt.issuer=${JWT_ISSUER:Mas Kilometros Backend}
jwt.subject=${JWT_SUBJECT:Mas Kilometros JWT Token}
jwt.expiration.hours=${JWT_EXP_HOURS:24}
jwt.prod.expiration.hours=${JWT_PROD_EXP_HOURS:1}
jwt.secret=${JWT_SECRET:jxgEQeXHuPq8VdbyYFNkANdudQ53YUn4}